version: "0.0.{build}"
branches:
  only:
    - master
skip_tags: true
max_jobs: 8
image: Visual Studio 2019
configuration: Debug
platform: x64
clone_depth: 1
init:
  - ps: '$env:SP_TAG=''suanPan-daily-''+(get-date -format "yyyyMMddHH")'
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build:
  parallel: true
  verbosity: minimal
# after_build:
#   - cmd: >-
#       7z a suanPan-win-openblas.zip
#       %APPVEYOR_BUILD_FOLDER%\README.md
#       %APPVEYOR_BUILD_FOLDER%\CHANGELOG.md
#       %APPVEYOR_BUILD_FOLDER%\MSVC\Debug\suanPan.exe
#       %APPVEYOR_BUILD_FOLDER%\MSVC\Debug\*.dll
#       %APPVEYOR_BUILD_FOLDER%\Libs\vs\*.dll
#       %APPVEYOR_BUILD_FOLDER%\Libs\gcc-win\lib*.dll
#       %APPVEYOR_BUILD_FOLDER%\Enhancement\AddAssociation.bat
#       %APPVEYOR_BUILD_FOLDER%\Enhancement\suanPan.sublime-completions
#       %APPVEYOR_BUILD_FOLDER%\Enhancement\suanPan.sublime-syntax
# artifacts:
#   - path: suanPan-win-openblas.zip
#     name: suanPan-win-openblas
# deploy:
#   - provider: GitHub
#     tag: $(SP_TAG)
#     release: $(SP_TAG)
#     auth_token:
#       secure: r32y0219p3bwKecKCkiRmFVDK91sbagx5Wy8/RO089zFk40psPa4e9SqCz4rWJ2K
#     artifact: suanPan-win-openblas
#     force_update: true
