name: Stable Release
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Compile
        run: |
          echo "SP_TIME=suanPan-daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          sudo apt update && sudo apt install libglu1-mesa-dev freeglut3-dev mesa-common-dev
          wget https://github.com/TLCFEM/vtk-prebuild/releases/download/latest/VTK-8.2.0-linux.tar.gz
          mkdir VTK-build && tar -xf VTK-8.2.0-linux.tar.gz -C VTK-build
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./VTK-build/lib/cmake/vtk-8.2/ .
          make -j4
          cp Enhancement/suanPan.sh .
          cp Enhancement/suanPan.sublime-completions .
          cp Enhancement/suanPan.sublime-syntax .
          cp Libs/gcc-linux/libtbb.so .
          cp Libs/gcc-linux/libtbb.so.2 .
          cp Libs/gcc-linux/libtbbmalloc.so .
          cp Libs/gcc-linux/libtbbmalloc.so.2 .
          cp Libs/gcc-linux/libtbbmalloc_proxy.so .
          cp Libs/gcc-linux/libtbbmalloc_proxy.so.2 .
          tar -cvzf suanPan-linux-openblas-vtk.tar.gz suanPan suanPan.sh suanPan.sublime-completions suanPan.sublime-syntax LICENSE README.md CHANGELOG.md libtbb.so libtbb.so.2 libtbbmalloc.so libtbbmalloc.so.2 libtbbmalloc_proxy.so libtbbmalloc_proxy.so.2
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: suanPan-linux-openblas-vtk
          path: suanPan-linux-openblas-vtk.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-linux-openblas-vtk.tar.gz
          asset_name: suanPan-linux-openblas-vtk.tar.gz
          tag: ${{ env.SP_TIME }}
          overwrite: true
  macos:
    runs-on: macos-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Compile
        run: |
          echo "SP_TIME=suanPan-daily-$(date +''%Y%m%d%H'')" >> $GITHUB_ENV
          sudo brew update && sudo brew install glfw3 glew
          wget https://github.com/TLCFEM/vtk-prebuild/releases/download/latest/VTK-8.2.0-macos.tar.gz
          mkdir VTK-build && tar -xf VTK-8.2.0-macos.tar.gz -C VTK-build
          export CC=gcc-9 && export CXX=g++-9 && export FC=gfortran-9
          cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_MULTITHREAD=ON -DUSE_HDF5=ON -DUSE_EXTERNAL_VTK=ON -DVTK_DIR=./VTK-build/lib/cmake/vtk-8.2/ .
          make -j4
          mkdir suanPan-macos-openblas-vtk
          cp suanPan suanPan-macos-openblas-vtk
          cp LICENSE suanPan-macos-openblas-vtk
          cp README.md suanPan-macos-openblas-vtk
          cp CHANGELOG.md suanPan-macos-openblas-vtk
          cp Enhancement/suanPan.sublime-completions suanPan-macos-openblas-vtk
          cp Enhancement/suanPan.sublime-syntax suanPan-macos-openblas-vtk
          cp Libs/gcc-mac/libtbb.dylib suanPan-macos-openblas-vtk
          cp Libs/gcc-mac/libtbbmalloc.dylib suanPan-macos-openblas-vtk
          cp Libs/gcc-mac/libtbbmalloc_proxy.dylib suanPan-macos-openblas-vtk
          tar cvzf suanPan-macos-openblas-vtk.tar.gz suanPan-macos-openblas-vtk
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: suanPan-macos-openblas-vtk
          path: suanPan-macos-openblas-vtk.tar.gz
      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: suanPan-macos-openblas-vtk.tar.gz
          asset_name: suanPan-macos-openblas-vtk.tar.gz
          tag: ${{ env.SP_TIME }}
          overwrite: true
